Committing svn revision 32529: Switch to kyoto cabinet for index storage for ZCP-9577

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -925,6 +925,8 @@ GSOAP_LIBS
 PKG_CONFIG
 VMIME_CFLAGS
 VMIME_LIBS
+KYOTOCABINET_CFLAGS
+KYOTOCABINET_LIBS
 ICAL_CFLAGS
 ICAL_LIBS
 WITH_CLUCENE_TRUE
@@ -994,6 +996,8 @@ YFLAGS
 PKG_CONFIG
 VMIME_CFLAGS
 VMIME_LIBS
+KYOTOCABINET_CFLAGS
+KYOTOCABINET_LIBS
 BOOST_ROOT'
 
 
@@ -1662,6 +1666,10 @@ Some influential environment variables:
   VMIME_CFLAGS
               C compiler flags for VMIME, overriding pkg-config
   VMIME_LIBS  linker flags for VMIME, overriding pkg-config
+  KYOTOCABINET_CFLAGS
+              C compiler flags for KYOTOCABINET, overriding pkg-config
+  KYOTOCABINET_LIBS
+              linker flags for KYOTOCABINET, overriding pkg-config
   BOOST_ROOT  Location of Boost installation
 
 Use these variables to override the choices made by `configure' or to help
@@ -4574,7 +4582,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4577 "configure"' > conftest.$ac_ext
+  echo '#line 4585 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7631,11 +7639,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7634: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7642: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7638: \$? = $ac_status" >&5
+   echo "$as_me:7646: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7921,11 +7929,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7924: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7932: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7928: \$? = $ac_status" >&5
+   echo "$as_me:7936: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8025,11 +8033,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8028: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8036: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8032: \$? = $ac_status" >&5
+   echo "$as_me:8040: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10402,7 +10410,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10405 "configure"
+#line 10413 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10502,7 +10510,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10505 "configure"
+#line 10513 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12903,11 +12911,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12906: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12914: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12910: \$? = $ac_status" >&5
+   echo "$as_me:12918: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13007,11 +13015,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13010: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13018: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13014: \$? = $ac_status" >&5
+   echo "$as_me:13022: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14605,11 +14613,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14608: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14616: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14612: \$? = $ac_status" >&5
+   echo "$as_me:14620: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14709,11 +14717,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14712: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14720: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14716: \$? = $ac_status" >&5
+   echo "$as_me:14724: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16929,11 +16937,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16932: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16940: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16936: \$? = $ac_status" >&5
+   echo "$as_me:16944: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17219,11 +17227,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17222: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17230: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17226: \$? = $ac_status" >&5
+   echo "$as_me:17234: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17323,11 +17331,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17326: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17334: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17330: \$? = $ac_status" >&5
+   echo "$as_me:17338: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -26121,6 +26129,120 @@ CXXFLAGS=$CXXFLAGS_system
 CPPFLAGS=$CPPFLAGS_system
 
 
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for KYOTOCABINET" >&5
+echo $ECHO_N "checking for KYOTOCABINET... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$KYOTOCABINET_CFLAGS"; then
+        pkg_cv_KYOTOCABINET_CFLAGS="$KYOTOCABINET_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"kyotocabinet\"") >&5
+  ($PKG_CONFIG --exists --print-errors "kyotocabinet") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_KYOTOCABINET_CFLAGS=`$PKG_CONFIG --cflags "kyotocabinet" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$KYOTOCABINET_LIBS"; then
+        pkg_cv_KYOTOCABINET_LIBS="$KYOTOCABINET_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"kyotocabinet\"") >&5
+  ($PKG_CONFIG --exists --print-errors "kyotocabinet") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_KYOTOCABINET_LIBS=`$PKG_CONFIG --libs "kyotocabinet" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        KYOTOCABINET_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "kyotocabinet"`
+        else
+	        KYOTOCABINET_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "kyotocabinet"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$KYOTOCABINET_PKG_ERRORS" >&5
+
+	{ { echo "$as_me:$LINENO: error: Package requirements (kyotocabinet) were not met:
+
+$KYOTOCABINET_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables KYOTOCABINET_CFLAGS
+and KYOTOCABINET_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (kyotocabinet) were not met:
+
+$KYOTOCABINET_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables KYOTOCABINET_CFLAGS
+and KYOTOCABINET_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables KYOTOCABINET_CFLAGS
+and KYOTOCABINET_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables KYOTOCABINET_CFLAGS
+and KYOTOCABINET_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	KYOTOCABINET_CFLAGS=$pkg_cv_KYOTOCABINET_CFLAGS
+	KYOTOCABINET_LIBS=$pkg_cv_KYOTOCABINET_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	:
+fi
+
+
+
+
 # Check whether --with-ical-prefix was given.
 if test "${with_ical_prefix+set}" = set; then
   withval=$with_ical_prefix; ICAL_PREFIX=${withval}
@@ -32332,6 +32454,8 @@ GSOAP_LIBS!$GSOAP_LIBS$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 VMIME_CFLAGS!$VMIME_CFLAGS$ac_delim
 VMIME_LIBS!$VMIME_LIBS$ac_delim
+KYOTOCABINET_CFLAGS!$KYOTOCABINET_CFLAGS$ac_delim
+KYOTOCABINET_LIBS!$KYOTOCABINET_LIBS$ac_delim
 ICAL_CFLAGS!$ICAL_CFLAGS$ac_delim
 ICAL_LIBS!$ICAL_LIBS$ac_delim
 WITH_CLUCENE_TRUE!$WITH_CLUCENE_TRUE$ac_delim
@@ -32370,8 +32494,6 @@ BOOST_SYSTEM_LDFLAGS!$BOOST_SYSTEM_LDFLAGS$ac_delim
 BOOST_SYSTEM_LIBS!$BOOST_SYSTEM_LIBS$ac_delim
 BOOST_FILESYSTEM_LDFLAGS!$BOOST_FILESYSTEM_LDFLAGS$ac_delim
 BOOST_FILESYSTEM_LIBS!$BOOST_FILESYSTEM_LIBS$ac_delim
-BOOST_DATE_TIME_LDFLAGS!$BOOST_DATE_TIME_LDFLAGS$ac_delim
-BOOST_DATE_TIME_LIBS!$BOOST_DATE_TIME_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -32413,6 +32535,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+BOOST_DATE_TIME_LDFLAGS!$BOOST_DATE_TIME_LDFLAGS$ac_delim
+BOOST_DATE_TIME_LIBS!$BOOST_DATE_TIME_LIBS$ac_delim
 ICU_CONFIG!$ICU_CONFIG$ac_delim
 ICU_CFLAGS!$ICU_CFLAGS$ac_delim
 ICU_CXXFLAGS!$ICU_CXXFLAGS$ac_delim
@@ -32423,7 +32547,7 @@ PROG_LIBS!$PROG_LIBS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 8; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 10; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
